
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 15 19:35:16 CST 2018
//----------------------------------------------------

package FGrammar;

/** CUP generated class containing symbol constants. */
public class SimbolosF {
  /* terminals */
  public static final int puntoYComa = 47;
  public static final int crearUsuario = 11;
  public static final int sucursal = 27;
  public static final int conjuncion = 48;
  public static final int precio = 37;
  public static final int size = 28;
  public static final int disyuncion = 49;
  public static final int correo = 41;
  public static final int img = 21;
  public static final int tienda = 17;
  public static final int coma = 29;
  public static final int direccion = 16;
  public static final int peticion = 3;
  public static final int de = 44;
  public static final int telefono = 14;
  public static final int inicioUsuario = 4;
  public static final int numero = 39;
  public static final int clave = 40;
  public static final int menos = 7;
  public static final int marca = 25;
  public static final int email = 15;
  public static final int propietario = 20;
  public static final int sobre = 10;
  public static final int EOF = 0;
  public static final int producto = 35;
  public static final int mas = 8;
  public static final int nombre = 12;
  public static final int error = 1;
  public static final int color = 26;
  public static final int user = 46;
  public static final int negacion = 50;
  public static final int por = 9;
  public static final int password = 6;
  public static final int llaveC = 31;
  public static final int obtener = 36;
  public static final int potencia = 23;
  public static final int id = 5;
  public static final int llaveA = 30;
  public static final int raizCuadrada = 22;
  public static final int tipo = 18;
  public static final int donde = 45;
  public static final int igualIgual = 51;
  public static final int cantidad = 24;
  public static final int apellido = 13;
  public static final int codigo = 19;
  public static final int dolar = 2;
  public static final int extraer = 43;
  public static final int parentesisC = 33;
  public static final int parentesisA = 32;
  public static final int asignacion = 34;
  public static final int consulta = 42;
  public static final int cadena = 38;
}

