
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 17 20:07:40 CST 2018
//----------------------------------------------------

package AGrammar;

/** CUP generated class containing symbol constants. */
public class SimbolosA {
  /* terminals */
  public static final int cadena = 30;
  public static final int nombre = 22;
  public static final int errorT = 17;
  public static final int modificar = 13;
  public static final int descripcion = 18;
  public static final int producto = 15;
  public static final int numero = 31;
  public static final int codigo = 21;
  public static final int precio = 29;
  public static final int lista = 19;
  public static final int acceso = 6;
  public static final int respuesta = 3;
  public static final int direccion = 28;
  public static final int marca = 24;
  public static final int asignacion = 11;
  public static final int propietario = 20;
  public static final int menos = 7;
  public static final int registro = 10;
  public static final int EOF = 0;
  public static final int dolar = 2;
  public static final int size = 26;
  public static final int verdadero = 8;
  public static final int cantidad = 27;
  public static final int id = 5;
  public static final int telefono = 23;
  public static final int eliminar = 14;
  public static final int usuario = 4;
  public static final int color = 25;
  public static final int error = 1;
  public static final int tienda = 12;
  public static final int falso = 9;
  public static final int sucursal = 16;
}

